trigger:
  - none

pool:
  name: Aztraining-Cat-Uk-Agentpool

variables:
- name: terraformVersion
  value: '1.5.7'
- name: resource_group_name
  value: 'rg-aztraining-ola'
- name: storage_account_name
  value: 'mystorageaccountola900'
- name: location
  value: 'uksouth'

stages:
- stage: Deploy
  jobs:
  - job: TerraformDeploy
    steps:
    - script: |
        echo "Installing Terraform..."
        curl -o terraform.zip https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform'

    - task: AzureCLI@2
      displayName: 'Login to Azure'
      inputs:
        azureSubscription: 'aztraining-cat-uk-azure-sc' # Replace with your Azure service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Setting up Azure authentication for Terraform..."
          az account show
    
    - script: |
        echo "Cleaning up Terraform state..."
        rm -rf .terraform
        rm -f terraform.tfstate terraform.tfstate.backup
        terraform init
      displayName: 'Clean and Reinitialize Terraform'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      

    - script: |
        echo "Validating Terraform configuration..."
        terraform validate
      displayName: 'Terraform Validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)'


    - script: |
        echo "Running Terraform Plan..."
        terraform -chdir=/terraform_pipeline/main.tf  plan \
          -var="resource_group_name=$(resource_group_name)" \
          -var="storage_account_name=$(storage_account_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

    - script: |
        echo "Applying Terraform configuration..."
        terraform apply -auto-approve \
          -var="resource_group_name=$(resource_group_name)" \
          -var="storage_account_name=$(storage_account_name)" \
          -var="location=$(location)"
      displayName: 'Terraform Apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)'







